### ISSUE TITLE
Develop case for bracelet

### ISSUE THREAD

**Issue by zandruchowitz** [csku25/ghest#16]
Research different options for case

Want it to be waterproof and durable

**Comment by jvick544** [comment]
"So for the 3D printing side of things I was suggested TPU, which would be water resistant and more flexible. 

We also have the option using a CNC, this opens us up to a lot of other plastic options such as HDPE, and also metals. I think 3D is probably the way to go for prototyping but a final housing may come out best with the CNC.

It was also recommended that we eventually change the mechanism that keeps the two half’s together if we’re going for water resistant/ proof - additionally adding a gusset to the design would help with this too "
